{
  "nbformat": 4,
  "nbformat_minor": 5,
  "metadata": {
    "kernelspec": {
      "display_name": "Python 3",
      "language": "python",
      "name": "python3"
    },
    "language_info": {
      "name": "python",
      "version": "3.10.0"
    }
  },
  "cells": [
    {
      "cell_type": "code",
      "metadata": {},
      "source": [
        "from typing import Annotated\r\n",
        "from typing_extensions import TypedDict\r\n",
        "from langgraph.graph import StateGraph, START, END\r\n",
        "from langgraph.graph.message import add_messages\r\n",
        "from dotenv import load_dotenv\r\n",
        "from langgraph.prebuilt import ToolNode\r\n",
        "from langchain_openai import ChatOpenAI\r\n",
        "from langgraph.checkpoint.memory import MemorySaver\r\n",
        "from langchain_core.messages import AIMessage, HumanMessage, SystemMessage, ToolMessage\r\n",
        "from typing import List, Any, Dict\r\n",
        "from sidekick_tools import other_tools\r\n",
        "import uuid\r\n",
        "import asyncio\r\n",
        "from datetime import datetime\r\n",
        "\r\n",
        "load_dotenv(override=True)\r\n",
        "\r\n",
        "\r\n",
        "class State(TypedDict):\r\n",
        "    messages: Annotated[List[Any], add_messages]\r\n",
        "    success_criteria: str\r\n",
        "\r\n",
        "\r\n",
        "class Sidekick:\r\n",
        "    def __init__(self):\r\n",
        "        self.worker_llm_with_tools = None\r\n",
        "        self.tools = None\r\n",
        "        self.graph = None\r\n",
        "        self.sidekick_id = str(uuid.uuid4())\r\n",
        "        self.memory = MemorySaver()\r\n",
        "        self.browser = None\r\n",
        "        self.playwright = None\r\n",
        "\r\n",
        "    async def setup(self):\r\n",
        "        self.tools = await other_tools()\r\n",
        "        worker_llm = ChatOpenAI(model=\"gpt-4o-mini\")\r\n",
        "        self.worker_llm_with_tools = worker_llm.bind_tools(self.tools)\r\n",
        "        await self.build_graph()\r\n",
        "\r\n",
        "    def worker(self, state: State) -> Dict[str, Any]:\r\n",
        "        system_message = f\"\"\"You are a helpful assistant that can use tools to complete tasks.\r\n",
        "    Your main task is to provide Google Scholar search results to the user.\r\n",
        "    You have a tool named google_scholar to search for papers on Google Scholar — call it with a focused query.\r\n",
        "    The current date and time is {datetime.now().strftime(\"%Y-%m-%d %H:%M:%S\")}\r\n",
        "\r\n",
        "    Success criteria for this turn:\r\n",
        "    {state.get(\"success_criteria\", \"Answer clearly using Scholar when relevant.\")}\r\n",
        "    \"\"\"\r\n",
        "\r\n",
        "        found_system_message = False\r\n",
        "        messages = state[\"messages\"]\r\n",
        "        for message in messages:\r\n",
        "            if isinstance(message, SystemMessage):\r\n",
        "                message.content = system_message\r\n",
        "                found_system_message = True\r\n",
        "\r\n",
        "        if not found_system_message:\r\n",
        "            messages = [SystemMessage(content=system_message)] + messages\r\n",
        "\r\n",
        "        response = self.worker_llm_with_tools.invoke(messages)\r\n",
        "        return {\"messages\": [response]}\r\n",
        "\r\n",
        "    def worker_router(self, state: State) -> str:\r\n",
        "        last_message = state[\"messages\"][-1]\r\n",
        "        if hasattr(last_message, \"tool_calls\") and last_message.tool_calls:\r\n",
        "            return \"tools\"\r\n",
        "        return \"end\"\r\n",
        "\r\n",
        "    async def build_graph(self):\r\n",
        "        graph_builder = StateGraph(State)\r\n",
        "\r\n",
        "        graph_builder.add_node(\"worker\", self.worker)\r\n",
        "        graph_builder.add_node(\"tools\", ToolNode(tools=self.tools))\r\n",
        "\r\n",
        "        graph_builder.add_conditional_edges(\r\n",
        "            \"worker\",\r\n",
        "            self.worker_router,\r\n",
        "            {\"tools\": \"tools\", \"end\": END},\r\n",
        "        )\r\n",
        "        graph_builder.add_edge(\"tools\", \"worker\")\r\n",
        "        graph_builder.add_edge(START, \"worker\")\r\n",
        "\r\n",
        "        self.graph = graph_builder.compile(checkpointer=self.memory)\r\n",
        "\r\n",
        "    async def run_superstep(self, message, success_criteria, history):\r\n",
        "        config = {\"configurable\": {\"thread_id\": self.sidekick_id}}\r\n",
        "\r\n",
        "        msgs = [HumanMessage(content=message)] if isinstance(message, str) else message\r\n",
        "        state = {\r\n",
        "            \"messages\": msgs,\r\n",
        "            \"success_criteria\": success_criteria or \"The answer should be clear and accurate\",\r\n",
        "        }\r\n",
        "        result = await self.graph.ainvoke(state, config=config)\r\n",
        "        last = result[\"messages\"][-1]\r\n",
        "        content = getattr(last, \"content\", None) or str(last)\r\n",
        "        user = {\"role\": \"user\", \"content\": message if isinstance(message, str) else str(message)}\r\n",
        "        reply = {\"role\": \"assistant\", \"content\": content}\r\n",
        "        return history + [user, reply]\r\n",
        "\r\n",
        "    def cleanup(self):\r\n",
        "        if self.browser:\r\n",
        "            try:\r\n",
        "                loop = asyncio.get_running_loop()\r\n",
        "                loop.create_task(self.browser.close())\r\n",
        "            except RuntimeError:\r\n",
        "                asyncio.run(self.browser.close())"
      ],
      "outputs": [],
      "execution_count": null
    }
  ]
}