{
  "nbformat": 4,
  "nbformat_minor": 5,
  "metadata": {
    "kernelspec": {
      "display_name": "Python 3",
      "language": "python",
      "name": "python3"
    },
    "language_info": {
      "name": "python",
      "version": "3.10.0"
    }
  },
  "cells": [
    {
      "cell_type": "code",
      "metadata": {},
      "source": [
        "from __future__ import annotations\r\n",
        "\r\n",
        "from typing import TypedDict\r\n",
        "\r\n",
        "from langchain_core.messages import HumanMessage, SystemMessage\r\n",
        "from langchain_openai import ChatOpenAI\r\n",
        "from langgraph.graph import END, START, StateGraph\r\n",
        "from pydantic import BaseModel, Field\r\n",
        "\r\n",
        "\r\n",
        "class BarInventory(BaseModel):\r\n",
        "    spirits: list[str] = Field(default_factory=list, description=\"Vodka, rum, gin, whiskey...\")\r\n",
        "\r\n",
        "    mixers: list[str] = Field(default_factory=list, description=\"Tonic, soda, juice, syrup...\")\r\n",
        "\r\n",
        "    fresh: list[str] = Field(default_factory=list, description=\"Limes, mint, berries...\")\r\n",
        "\r\n",
        "    tools: list[str] = Field(default_factory=list, description=\"Shaker, blender...\")\r\n",
        "    \r\n",
        "    vibe: str = Field(default=\"\", description=\"What kind of drinks they want tonight.\")\r\n",
        "\r\n",
        "\r\n",
        "class BarState(TypedDict, total=False):\r\n",
        "    raw_input: str\r\n",
        "    inventory: str\r\n",
        "    available_drinks: str\r\n",
        "    stretch_drinks: str\r\n",
        "    menu: str\r\n",
        "\r\n",
        "\r\n",
        "_llm = ChatOpenAI(model=\"gpt-4o-mini\", temperature=0.6)\r\n",
        "_parser = _llm.with_structured_output(BarInventory)\r\n",
        "\r\n",
        "\r\n",
        "def parse_bar(state: BarState) -> dict:\r\n",
        "    text = state.get(\"raw_input\", \"\")\r\n",
        "    result: BarInventory = _parser.invoke([\r\n",
        "        SystemMessage(content=(\r\n",
        "            \"Pull out what this person has in their home bar. \"\r\n",
        "            \"Spirits, mixers, fresh ingredients, bar tools and what kind of drinks they like. \"\r\n",
        "            \"If something's vague just make a reasonable guess.\"\r\n",
        "        )),\r\n",
        "        HumanMessage(content=text),\r\n",
        "    ])\r\n",
        "\r\n",
        "\r\n",
        "    summary = (\r\n",
        "        f\"Spirits: {', '.join(result.spirits) or 'none listed'}\\n\"\r\n",
        "        f\"Mixers: {', '.join(result.mixers) or 'none listed'}\\n\"\r\n",
        "        f\"Fresh: {', '.join(result.fresh) or 'none listed'}\\n\"\r\n",
        "        f\"Tools: {', '.join(result.tools) or 'just glasses'}\\n\"\r\n",
        "        f\"Vibe: {result.vibe or 'open to anything'}\"\r\n",
        "    )\r\n",
        "\r\n",
        "    return {\"inventory\": summary}\r\n",
        "\r\n",
        "\r\n",
        "def mix_now(state: BarState) -> dict:\r\n",
        "    prompt = (\r\n",
        "        f\"Home bar inventory:\\n{state['inventory']}\\n\\n\"\r\n",
        "        \"Suggest 3-4 cocktails they can make RIGHT NOW with only what's listed. \"\r\n",
        "        \"For each one give the name, ingredients with rough amounts and how to make it. \"\r\n",
        "        \"Don't sneak in anything they don't have. \"\r\n",
        "        \"If the bar is bare just suggest highballs or neat pours.\"\r\n",
        "    )\r\n",
        "    return {\"available_drinks\": _llm.invoke(prompt).content}\r\n",
        "\r\n",
        "\r\n",
        "def mix_soon(state: BarState) -> dict:\r\n",
        "    prompt = (\r\n",
        "        f\"Home bar inventory:\\n{state['inventory']}\\n\\n\"\r\n",
        "        f\"Already suggested these:\\n{state.get('available_drinks', '')}\\n\\n\"\r\n",
        "        \"Now suggest 2-3 more drinks they could make if they picked up \"\r\n",
        "        \"1-2 extra things each. List what they'd need to buy. \"\r\n",
        "        \"Keep it to cheap, easy-to-find stuff.\"\r\n",
        "    )\r\n",
        "\r\n",
        "\r\n",
        "    return {\"stretch_drinks\": _llm.invoke(prompt).content}\r\n",
        "\r\n",
        "\r\n",
        "def build_menu(state: BarState) -> dict:\r\n",
        "    prompt = (\r\n",
        "        \"Put together a drink menu. Use these sections:\\n\"\r\n",
        "        \"## Tonight's Menu\\n(what they can make now)\\n\\n\"\r\n",
        "        \"## Worth a Store Run\\n(drinks needing 1-2 extra ingredients + what to grab)\\n\\n\"\r\n",
        "        \"## Quick Shopping List\\n(all missing ingredients in one spot)\\n\\n\"\r\n",
        "        f\"Inventory:\\n{state['inventory']}\\n\\n\"\r\n",
        "        f\"Ready now:\\n{state.get('available_drinks', '')}\\n\\n\"\r\n",
        "        f\"With extras:\\n{state.get('stretch_drinks', '')}\\n\\n\"\r\n",
        "        \"Sound like a friend who knows drinks, not a cocktail textbook.\"\r\n",
        "    )\r\n",
        "\r\n",
        "\r\n",
        "    return {\"menu\": _llm.invoke(prompt).content}\r\n",
        "\r\n",
        "\r\n",
        "\r\n",
        "def build_graph():\r\n",
        "    g = StateGraph(BarState)\r\n",
        "    g.add_node(\"parse_bar\", parse_bar)\r\n",
        "    g.add_node(\"mix_now\", mix_now)\r\n",
        "    g.add_node(\"mix_soon\", mix_soon)\r\n",
        "    g.add_node(\"build_menu\", build_menu)\r\n",
        "    g.add_edge(START, \"parse_bar\")\r\n",
        "    g.add_edge(\"parse_bar\", \"mix_now\")\r\n",
        "    g.add_edge(\"mix_now\", \"mix_soon\")\r\n",
        "    g.add_edge(\"mix_soon\", \"build_menu\")\r\n",
        "    g.add_edge(\"build_menu\", END)\r\n",
        "    return g.compile()\r\n",
        "\r\n",
        "\r\n",
        "def run_bartender(user_text: str) -> str:\r\n",
        "    graph = build_graph()\r\n",
        "    result = graph.invoke({\"raw_input\": user_text})\r\n",
        "    return result.get(\"menu\", \"Couldn't put a menu together. Try again?\")\r\n",
        ""
      ],
      "outputs": [],
      "execution_count": null
    }
  ]
}